### PR TITLE
Add option to make the bar transparent

### PR DESCRIPTION
**Pull request by mcfry**
Allow the spark to be used as an overlay on the player's mana bar.

### CODE REVIEW

**Comment by smp4903** [comment]
Hey @mcfry 

Damn, should've seen this earlier. Been sick for two weeks..
You addressed some very critical issues here, and I see you actually did it much like I did.
However, your approach with using actual player MP5 (duuh). I applied a running average on all ticks.

I'll review your request and evaluate the two :-)

Thanks a lot!

**Comment by mcfry** [comment]
Hey! @smp4903 

I thought about using averages but decided against it because:
It's inaccurate for the first few ticks after loading in, and saving the last average isn't guaranteed to be correct
It's inaccurate for a few ticks after a number of events, including: swapping gear, buffs/debuffs, changing talents, etc

If possible, I think having a more precisely defined limit is better. I use the addon ItemRack and am frequently swapping gear in the middle of combat, so running averages doesn't fit my use case. Some players also swap to a set of gear before using Evocate to increase their mana returned, which will probably report inaccurately in FSR with running averages. I'm sure there are other scenarios, these are just some that I relate to as a mage.

That said, I noticed in my commit that the spark extends past the bar semi-frequently. Was wondering if you noticed this as well and was the reason you changed it. If nothing else, I'll debug this for my personal use at some point or look into other alternatives. (Instead of tracking ticks by mp5, perhaps hashing ticks by seconds and doing something like % 2 will keep things consistent?)

**Comment by smp4903** [comment]
@mcfry you are right on most points. The reason why the ticks continued across the screen was three-fold:

1. Not all valid ticks were registered in order to reset the timer. 
2. There is an irregular delay between ticks sometimes, that I have found no way of predicting.
3. The spark's relative position to the status bar was not limited. 

Point 3 has been solved, point 2 remains a mystery. However, point 1 was the main reason I used the running averages. I had a lot more true positives. But it is definitely a lacking solution on the points on you list above, I acknowledge that entirely.

One of the primary reasons I had to rush the merge in the direction of using running averages was actually also because of localization issues with yours. 

A few users were experiencing issues on non-EnGB clients (German), simply because the classes are not called the same in all languages. Your contribution did inspire me to use localized spell names for checking buffs, so that's awesome. Perhaps there's a way to get localized class names from the API. 

I think we should give the more precise solution a go again. We need to keep it simple for maximum traceability.

Thoughts?

**Comment by mcfry** [comment]
Quick thoughts:
If the spark reaches the end of the bar and a valid tick has not been observed, I think it should pause there instead of recycling.
If the ticks aren't too irregular, then a tick time solution should still work (i.e. it doesn't matter if the tick is from Blessing of Wisdom, etc or mp5 if the 2s tick recordings are .1 ms apart). If they're larger than that then you're back to needing a lower limit on mp5 ticks (constants for a perfect solution).

Will take a look this weekend.

**Pull request merged**
